### ISSUE TITLE
Method 'retrieveItem(with:)' in non-final class 'Item' must return 'Self' to conform to protocol 'SpotlightRetrievable'

### ISSUE THREAD

**Issue by iain-reid** [felix-dumit/EasySpotlight#2]
Hi Felix. I'm hoping to use this library with Realm in my app - but am getting this error:

**Method 'retrieveItem(with:)' in non-final class 'Item' must return 'Self' to conform to protocol 'SpotlightRetrievable'**

I have a Realm Object Class called 'Item'. The project is using Swift 4.2. 

![2018-11-30 at 11 47](https://user-images.githubusercontent.com/1871804/49287757-91038980-f496-11e8-909a-08209a935a6d.jpg)

Any help would be incredibly useful as I'm not sure why I'm getting this error - could it be a Swift 4.2 issue?

Thanks.

**Comment by felix-dumit** [comment]
Hi Ian,

I believe if you make your class final it should solve the issue.
I.e. ```final class Item: Object {}```

This is because the protocol has a `Self` type as the return type of that method, and if you could subclass your class then it would be ambiguous what type that function would return for the parent and child classes.

**Comment by iain-reid** [comment]
Perfect - Thanks for your help!
